name: Example
options:
  minimumXcodeGenVersion: 1.11.2
  bundleIdPrefix: jp.toshi0383
targets:
  Example:
    platform: iOS
    type: application
    sources:
      - Example/
    dependencies:
      - carthage: RxCocoa
      - carthage: RxSwift
      - target: VideoPlayerManager
  VideoPlayerManager:
    platform: iOS
    type: framework
    sources:
      - Sources/
    dependencies:
      - carthage: RxCocoa
      - carthage: RxSwift
  VideoPlayerManagerTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - path: Tests/VideoPlayerManagerTests/
        name: VideoPlayerManagerTests
        excludes:
        - "XCTestManifests.swift"
    dependencies:
      - target: VideoPlayerManager
      - carthage: RxCocoa
      - carthage: RxSwift
      - carthage: RxTest
    scheme:
      testTargets:
        - VideoPlayerManagerTests
      gatherCoverageData: true
