name: Example
options:
  minimumXcodeGenVersion: 1.11.2
  bundleIdPrefix: jp.toshi0383
targets:
  Example:
    platform: iOS
    type: application
    sources:
      - Example/
    dependencies:
      - carthage: RxCocoa
      - carthage: RxSwift
      - target: RxAVPlayer
  RxAVPlayer:
    platform: iOS
    type: framework
    sources:
      - Sources/
    dependencies:
      - carthage: RxCocoa
      - carthage: RxSwift
